blank_issues_enabled: false
contact_links:
  - name: ğŸ“ Contributing Guidelines
    url: https://github.com/teociaps/azdo-workitem-decomposer/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project
  - name: ğŸ’¬ Discussions
    url: https://github.com/teociaps/azdo-workitem-decomposer/discussions
    about: Ask questions and discuss about the project with the community
  - name: ğŸ†˜ Support
    url: https://github.com/teociaps/azdo-workitem-decomposer/discussions/categories/q-a
    about: Get help from the community in Q&A discussions
